pkey: check new openssh format key type
paramiko/paramiko pull request #1606
Opened 2020-01-21 08:32 UTC by ploxiln

needs to reliably fail with SSHException,
for SSHClient._auth() to detect type class for key_filenames

fixes #1590

2021-06-13 07:30 UTC, calebstewart commented
Is there anything pending for this to be merged? This appears to provide a fix for #1839, which is plaguing me currently.

2021-07-02 02:53 UTC, onstring commented
wonder when could we get this fix merged? I am troubled with an issue caused by this.

2021-07-07 04:05 UTC, jeffctr commented
I run with the changes suggested in this PR but ti does not work either. Is there any solution to this? 

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1898, in run
    self._check_banner()
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2055, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2050, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 360, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 572, in _read_timeout
    raise EOFError()
EOFError
```

2021-08-09 06:50 UTC, vinit-tribes commented
Any progress on this yet, I am as well stuck at the same issue

2021-12-10 11:49 UTC, Mooreel commented
This still is an issue. I can't use RSA, it always treats my keys as DSA

2021-12-11 07:14 UTC, ploxiln commented
For what it's worth, this is fixed in my fork "paramiko-ng" since version 2.6
  * releases/changes: https://github.com/ploxiln/paramiko-ng/releases
  * install instructions: https://github.com/ploxiln/paramiko-ng#installation

2022-01-12 07:28 UTC, voryzen commented
+1 for merging this.

Using paramiko-ng in the meantime

2022-03-10 11:33 UTC, m1009d commented
Hi guys,
seems like this issue is not in `2.8.10`, for me everything is working in this version but not in the latest `2.9.2`.

2022-04-09 08:38 UTC, aasifkhan7 commented
what is the blocker for merging this guys? @ploxiln

2022-04-09 08:43 UTC, aasifkhan7 commented
> Hi guys, seems like this issue is not in `2.8.1`, for me everything is working in this version but not in the latest `2.9.2`.

+1 . this worked for me as well. 

Also, what is the blocker for merging this @ploxiln ?

2022-04-09 17:09 UTC, ploxiln commented
It needs attention from the maintainer, which I am not.

In the meantime, you could possibly use my fork https://github.com/ploxiln/paramiko-ng/

2022-04-11 16:45 UTC, bskinn commented
This issue/PR is milestoned for the next bugfix paramiko release. Timing will depend on @bitprophet's prioritization among all of paramiko, invoke and fabric, within his weekly time allotted to open-source, so a precise timeline/due-date isn't really available.

2022-05-24 13:54 UTC, bskinn requested changes
Minor bit of docs

2022-07-07 18:23 UTC, simon04 commented on paramiko/pkey.py
> +    def _read_private_key_file(self, tag, pfx, filename, password=None):
Suggestion for docstring:

```diff
         :param str tag: ``"RSA"`` or ``"DSA"``, the tag used to mark the
             data block.
+        :param str pfx: expected (prefix of) public key type, e.g. "ssh-rsa".
         :param str filename: name of the file to read.
```

2023-11-15 08:22 UTC, jeffguorg commented
try this if you can't wait

```bash
ssh-keygen -m PEM -p
```

2025-03-17 02:36 UTC, closed without merging